### ISSUE TITLE
Open-source license

### ISSUE THREAD

**Issue by nukmuk** [eelislynne/SQF-Wiki-VSC#3]
Hello, I would like to fork this project, but it has no license and GitHub's terms don't allow modifying works that don't have a license. Could an open-source license be added?

**Comment by eelislynne** [comment]
Added MIT license to allow forking for private/public/commercial purposes.

If you're interested in adding new functionality or such, you can always open a pull request and I will most likely accept it. This way updates would get pushed to existing users of this plugin.
